# Generated by Django 5.0 on 2025-09-17 19:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nikhil Dodda', max_length=100)),
                ('tagline', models.CharField(default='Applied AI Engineer', max_length=200)),
                ('bio', models.TextField(default='Building intelligent applications that solve real business problems.')),
                ('location', models.CharField(default='Ashburn, Virginia', max_length=100)),
                ('email', models.EmailField(default='hello@nikhildodda.dev', max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('calendar_url', models.URLField(blank=True, help_text='Cal.com booking link')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('hero_video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('meta_description', models.TextField(default='Applied AI Engineer specializing in production LLM systems and scalable cloud infrastructure.', max_length=160)),
                ('meta_keywords', models.CharField(default='AI Engineer, Machine Learning, LLM, RAG, Python, AWS', max_length=500)),
                ('years_experience', models.IntegerField(default=2)),
                ('projects_completed', models.IntegerField(default=5)),
                ('technologies_mastered', models.IntegerField(default=20)),
                ('coffee_consumed', models.IntegerField(default=1000, help_text='Fun stat!')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='techcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Tech Categories'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category__order', 'name'], 'verbose_name_plural': 'Technologies'},
        ),
        migrations.RemoveField(
            model_name='techcategory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='code_snippets',
            field=models.JSONField(default=list, help_text='[{"title": "Core Algorithm", "language": "python", "code": "..."}]'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='What you learned (Markdown supported)'),
        ),
        migrations.AddField(
            model_name='technology',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tagline',
            field=models.CharField(help_text='One-line description', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='projects.technology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='challenges_solved',
            field=models.TextField(blank=True, help_text='Technical challenges overcome (Markdown supported)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='key_features',
            field=models.JSONField(default=list, help_text='["Feature 1", "Feature 2"]'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='performance_metrics',
            field=models.JSONField(default=list, help_text='[{"metric": "Latency", "improvement": "40% faster"}]'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='problem_statement',
            field=models.TextField(help_text='What problem does this solve? (Markdown supported)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='solution_approach',
            field=models.TextField(help_text='How did you solve it? (Markdown supported)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='technical_architecture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Architecture diagram', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='technology_justification',
            field=models.TextField(help_text='Why these technologies? (Markdown supported)'),
        ),
        migrations.AlterField(
            model_name='techcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technology',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.CreateModel(
            name='CareerHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date_range', models.CharField(help_text="e.g., 'Jan 2024 - Present'", max_length=100)),
                ('description', models.TextField()),
                ('metrics', models.JSONField(default=list, help_text='[{"metric": "Latency Reduction", "value": "40%"}]')),
                ('order', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(blank=True, to='projects.technology')),
            ],
            options={
                'ordering': ['-order', '-id'],
            },
        ),
    ]
