# Generated by Django 5.0 on 2025-09-17 17:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField(help_text='Markdown supported')),
                ('category', models.CharField(choices=[('ai-trends', 'AI Trends'), ('technical', 'Technical Deep Dive'), ('industry', 'Industry Insights'), ('tutorial', 'Tutorial'), ('opinion', 'Opinion')], max_length=20)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('reading_time', models.IntegerField(editable=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CareerHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Markdown supported')),
                ('metrics', models.JSONField(default=list, help_text='List of achievements with metrics')),
                ('order', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-order', '-is_current'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nikhil Dodda', max_length=100)),
                ('tagline', models.CharField(default='Applied AI Engineer', max_length=200)),
                ('bio', models.TextField(help_text='Main bio for about page')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('resume_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='file')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('cal_com_username', models.CharField(blank=True, max_length=50)),
                ('meta_description', models.TextField(max_length=160)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
