# Generated by Django 5.0 on 2025-09-17 17:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bluesky_handle',
            field=models.CharField(blank=True, default='@devdn.bsky.social', help_text='Your Bluesky handle (e.g., @username.bsky.social)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_resume_text',
            field=models.CharField(blank=True, default='Download Resume', help_text='Custom text for resume download button', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_resume_download',
            field=models.BooleanField(default=False, help_text='Show resume download button (only if resume_file is uploaded)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bio',
            field=models.TextField(default='Applied AI Engineer with a passion for building intelligent systems that solve real-world problems. Currently working at VS SOFT, I specialize in LLM applications, RAG systems, and production ML infrastructure.', help_text='Main bio for about page'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='cal_com_username',
            field=models.CharField(blank=True, default='dnpro', help_text='Your Cal.com username for scheduling', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='hello@nikhildodda.dev', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='github_url',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Optional: LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(default='Applied AI Engineer specializing in production LLM systems, RAG architectures, and scalable ML infrastructure. Building intelligent applications that solve real business problems.', max_length=160),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.CharField(default='AI Engineer, Machine Learning, LLM, RAG Systems, Python, AWS, MLOps, Applied AI, Nikhil Dodda', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='resume_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tagline',
            field=models.CharField(default='Applied AI Engineer specializing in production LLM systems and scalable cloud infrastructure', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Optional: Twitter/X profile URL'),
        ),
    ]
