# Generated by Django 5.0 on 2025-09-17 17:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField(help_text='Markdown supported')),
                ('category', models.CharField(choices=[('ai-trends', 'AI Trends'), ('technical', 'Technical Deep Dive'), ('industry', 'Industry Insights'), ('tutorial', 'Tutorial'), ('opinion', 'Opinion')], max_length=20)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('reading_time', models.IntegerField(editable=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
